import { Inter } from 'next/font/google';
import './globals.css';
import { IdiomaProvider } from '../Context/IdiomaContext.js';
import Menu from '../componets/Navbar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="flex flex-col items-center relative  min-h-screen px-2 pb-4 mx-auto w-full">
				<IdiomaProvider>
					<Menu />
					{children}
				</IdiomaProvider>
			</body>
		</html>
	);
}
